"use client";

import { useState, useRef } from "react";
import TrackedQuill from "../components/TrackedQuill";

export default function Home() {
  const [currentText, setCurrentText] = useState("Start typing here...");
  const applyNewContentRef = useRef<((newContent: string) => void) | null>(null);

  const getMockLLMResponse = () => {
    // Mock LLM response - this will not change for any reason in the current implementation
    return `This is a mock LLM response that simulates what an AI language model might return.
      It includes some sample text that demonstrates how the diff tracking works when new content is applied to the editor.
      You can see insertions highlighted in yellow and deletions shown with strikethrough formatting.`
      ;
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const llmText = getMockLLMResponse();
    
    // Apply the new content as a diff instead of replacing the component
    if (applyNewContentRef.current) {
      applyNewContentRef.current(llmText);
    } else {
      // Fallback: if the apply function is not available, update the text state
      setCurrentText(llmText);
    }
  };

  const handleApplyNewContentRegistration = (applyFn: (newContent: string) => void) => {
    applyNewContentRef.current = applyFn;
  };

  return (
    <main className="bg-pageBg min-h-screen">
      <div className="flex flex-col md:flex-row min-h-screen">
        <section className="w-full md:w-1/2 bg-placeholder p-6 flex flex-col">
          {/* Lavender placeholder box */}
          <div className="bg-lavender border-dotted border-2 border-fuchsia-600 opacity-65 p-8 mb-6 flex-1 flex items-center justify-center min-h-[200px]">
            <span className="text-muted text-lg">placeholder</span>
          </div>

          <h2 className="text-medium font-semibold mb-4">Get mock LLM response</h2>

          {/* Form with white background */}
          <div className="bg-white rounded-lg p-6 shadow-sm">
            <form className="space-y-4" onSubmit={handleFormSubmit}>
              <div>
                <input className="w-full border-border rounded px-3 py-2" name="single" placeholder="Reply to George" type="text" />
              </div>
              <div className="flex justify-end">
                <button type="submit" className="px-4 py-2 bg-gray-900 hover:bg-gray-800 text-white rounded font-small">
                  Send message
                </button>
              </div>
            </form>
          </div>
        </section>
        <section className="w-full md:w-1/2 bg-white p-6 flex flex-col">
          {/* Structured text content */}
          <div className="mb-6">
            <h1 className="text-2xl font-bold mb-2">Landing Page A/B Test</h1>
            <p className="text-gray-600">
              This is a short description of what the study is about, generated by George. It should 
              sound really good and concise. Lorem ipsum...
            </p>
          </div>
        
          <div className="w-full h-full min-h-[300px] flex-1">
            {/* TrackedQuill is a client component that shows insert/delete highlights */}
            <TrackedQuill 
              initial={currentText} 
              onApplyNewContent={handleApplyNewContentRegistration}
            />
          </div>
        </section>
      </div>
    </main>
  );
}

